---
title: "Introduction to goshawk"
date: "2022-03-09"
output:
    rmarkdown::html_document:
        theme: "spacelab"
        highlight: "kate"
        toc: true
        toc_float: true
vignette: >
    %\VignetteIndexEntry{Introduction to goshawk}
    %\VignetteEngine{knitr::rmarkdown}
    %\VignetteEncoding{UTF-8}
editor_options:
    markdown:
        wrap: 72
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Introduction

This vignette shows the general purpose and syntax of the `goshawk` R package.
The `goshawk` R package contains analytical functions for primarily creating longitudinal visualizations useful for clinical trials and other statistical analysis.

## Common Clinical Trials Analyses

The package provides several functions to create graphs used for clinical trials and other statistical analyses.

data visualizations:

- box plots
- correlation and scatter plots
- density distribution plots
- line plots
- spaghetti plots

data tables:

- box, density and line plots are accompanied by tables displaying descriptive statistics

data brushing:

- box, correlation and spaghetti plots include data brushing functionality used to display details
of data points displayed in the plots

The reference of `goshawk` functions is available on [the goshawk website functions reference](https://insightsengineering.github.io/goshawk/latest-tag/reference/index.html).

The `goshawk` functions used for plot generation are `g_` prefixed.
All `goshawk` plot functions are listed on [the goshawk website functions reference](https://insightsengineering.github.io/goshawk/latest-tag/reference/index.html) and
include examples of data pre-processing and function usage. Please see the Articles
for more information on data pre-processing and data expectations for `goshawk`.

## Interactive Apps

The `goshawk` outputs can be easily accommodated into `shiny` apps.
We recommend applying `goshawk` outputs into `teal` apps.
The [`teal` package](https://insightsengineering.github.io/teal/) is a shiny-based interactive exploration framework for analyzing data.
`teal` shiny apps with `goshawk` outputs are available in the [`teal.goshawk` package](https://insightsengineering.github.io/teal.goshawk/).


## Data Requirements
`goshawk` and `teal.goshawk` have similar data related requirements so we chose to document those in the `teal.goshawk` package.

**For more detail on these requirements please visit the [teal.goshawk website](https://insightsengineering.github.io/teal.goshawk/).**

## Summary

In summary, `goshawk` contains functions for creating primarily longitudinal visualizations used in clinical trials and other statistical analyses. The design of the package gives users a lot of flexibility to meet the analysis needs in a regulatory or exploratory reporting context.

**For more information please explore [the goshawk website](https://insightsengineering.github.io/goshawk/).**
